version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "/app/node_modules"
      - "./:/app"
  backend:
    image: mausampaio/devsindev-api:latest
    ports:
      - 8080:1337
  seed:
    depends_on:
      - backend
    image: mausampaio/devsindev-seed:latest
    environment:
      SAILS_PORT: 1337
      SAILS_HOST: backend
      WAIT_HOSTS: backend:1337